begin;
create temporary table identities(kind text primary key,id uuid not null default gen_random_uuid());
insert into identities(kind) values('a'),('b'),('super');
create temporary table results(name text primary key);
grant select on identities to authenticated,anon,service_role;
create function pg_temp.check_result(ok boolean,label text) returns void language plpgsql security definer as $$ begin if ok is distinct from true then raise exception 'TEST FAILED: %',label; end if; insert into results values(label); end $$;
create function pg_temp.denied(command text,label text) returns void language plpgsql as $$ declare rejected boolean := false; begin begin execute command; exception when others then rejected := true; end; perform pg_temp.check_result(rejected,label); end $$;
do $$ declare ns text; begin select nspname into ns from pg_namespace where oid=pg_my_temp_schema(); execute format('grant usage on schema %I to authenticated,anon,service_role',ns); end $$;
insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data,raw_app_meta_data,aud,role)
select id,'fadtwibbon-test-'||id::text||'@example.invalid',now(),'{"role":"super_admin"}','{}','authenticated','authenticated' from identities;
update public.profiles set status='active' where user_id in(select id from identities);
update public.user_roles set role='super_admin' where user_id=(select id from identities where kind='super');
select pg_temp.check_result((select role='admin' from public.user_roles where user_id=(select id from identities where kind='a')),'registration ignores editable privileged metadata');

set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',(select id from identities where kind='a'),'role','authenticated')::text,true);
select public.save_campaign(null,'Tenant A','test-'||(select id from identities where kind='a')::text,'','Caption A',null);
select pg_temp.denied('update public.profiles set status=''active''','profile privilege mutation denied');
select pg_temp.denied('update public.user_roles set role=''super_admin''','role escalation denied');
select pg_temp.denied('select public.moderate_account('''||(select id from identities where kind='b')::text||''',''suspended'')','admin moderation denied');
select pg_temp.denied('select public.commit_template(null,null,null,null,null,1,1,1,null)','direct template commit denied');
select pg_temp.denied('select public.accept_download(gen_random_uuid(),gen_random_uuid(),repeat(''a'',64))','direct analytics RPC denied');
reset role;
create temporary table test_campaigns as select c.* from public.campaigns c where c.owner_id in(select id from identities);
grant select on test_campaigns to authenticated,anon,service_role;
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',(select id from identities where kind='b'),'role','authenticated')::text,true);
select public.save_campaign(null,'Tenant B','test-'||(select id from identities where kind='b')::text,'','Caption B',null);
select pg_temp.check_result((select count(*)=0 from public.campaigns where owner_id=(select id from identities where kind='a')),'tenant cross-read blocked');
select pg_temp.denied('select public.save_campaign('''||(select id from test_campaigns limit 1)::text||''',''Hacked'',''hacked-slug'','''','''','''||(select updated_at from test_campaigns limit 1)::text||''')','tenant cross-write blocked');
select pg_temp.denied('insert into storage.objects(bucket_id,name) values(''templates'',''foreign/file.png'')','unvalidated storage upload denied');
select pg_temp.check_result((select (public.dashboard_stats(false)->>'campaigns')::int=1),'statistics limited to own tenant');
set local role anon;
select pg_temp.denied('select * from public.campaigns','anonymous private campaign read denied');
select pg_temp.denied('insert into storage.objects(bucket_id,name) values(''templates'',''anon/file.png'')','anonymous storage upload denied');
select pg_temp.denied('insert into public.download_events(campaign_id,event_token) values(gen_random_uuid(),gen_random_uuid())','anonymous raw analytics insert denied');
reset role;

create temporary table asset as select gen_random_uuid() id,id as campaign_id,owner_id,updated_at from test_campaigns limit 1;
alter table asset add column path text;
update asset set path=owner_id::text||'/'||campaign_id::text||'/'||id::text||'.png';
insert into storage.objects(bucket_id,name) select 'templates',path from asset;
grant select on asset to authenticated,service_role;
set local role service_role;
select public.commit_template((select id from identities where kind='a'),(select campaign_id from asset),(select updated_at from asset),(select id from asset),(select path from asset),100,1080,1080,repeat('a',64));
select pg_temp.check_result(public.public_campaign('test-'||(select id from identities where kind='a')::text) is null,'draft not public');
reset role;
insert into storage.objects(bucket_id,name) select 'published-templates',campaign_id::text||'/'||id::text||'.png' from asset;
set local role service_role;
select public.publish_campaign((select id from identities where kind='a'),(select campaign_id from asset),(select updated_at from public.campaigns where id=(select campaign_id from asset)));
select pg_temp.check_result(not(public.public_campaign('test-'||(select id from identities where kind='a')::text) ? 'owner_id'),'public projection excludes owner metadata');
reset role;
create temporary table event_token as select gen_random_uuid() token;
grant select on event_token to service_role;
set local role service_role;
select pg_temp.check_result(public.accept_download((select campaign_id from asset),(select token from event_token),repeat('a',64))='accepted','valid event accepted');
select pg_temp.check_result(public.accept_download((select campaign_id from asset),(select token from event_token),repeat('a',64))='duplicate','event deduplicated');
select pg_temp.check_result((select download_events_count=1 from public.campaign_daily_stats where campaign_id=(select campaign_id from asset)),'duplicate does not inflate aggregate');
do $$ declare result text; begin for i in 1..30 loop result := public.accept_download((select campaign_id from asset),gen_random_uuid(),repeat('a',64)); end loop; perform pg_temp.check_result(result='rate_limited','source rate limit enforced'); end $$;
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',(select id from identities where kind='a'),'role','authenticated')::text,true);
select pg_temp.denied('select public.save_campaign('''||(select campaign_id from asset)::text||''',''Title'',''changed-slug'','''','''','''||(select updated_at from public.campaigns where id=(select campaign_id from asset))::text||''')','published slug immutable');
select pg_temp.denied('select public.set_campaign_status('''||(select campaign_id from asset)::text||''',''draft'',''2000-01-01'')','optimistic concurrency enforced');
select set_config('request.jwt.claims',jsonb_build_object('sub',(select id from identities where kind='super'),'role','authenticated')::text,true);
select pg_temp.check_result((select count(*)=2 from public.campaigns where owner_id in(select id from identities)),'superadmin can read both tenants');
select public.moderate_account((select id from identities where kind='a'),'suspended');
set local role service_role;
select pg_temp.check_result(public.public_campaign('test-'||(select id from identities where kind='a')::text) is null,'suspension hides public campaigns');
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',(select id from identities where kind='a'),'role','authenticated')::text,true);
select pg_temp.denied('select public.save_campaign(null,''Suspended'',''suspended-test'','''','''',null)','suspended active session cannot write');
select pg_temp.check_result((select count(*)=0 from storage.objects where bucket_id='templates' and name=(select path from asset)),'suspended private storage read blocked');
select set_config('request.jwt.claims',jsonb_build_object('sub',(select id from identities where kind='super'),'role','authenticated')::text,true);
select public.moderate_account((select id from identities where kind='a'),'active');
set local role service_role;
select pg_temp.check_result(public.public_campaign('test-'||(select id from identities where kind='a')::text) is not null,'reactivation restores public campaign');
reset role;
select jsonb_build_object('passed',count(*),'tests',jsonb_agg(name order by name),'isolation','all test records rolled back') as report from results;
rollback;
